project:
  type: website
  output-dir: docs

website:
  title: Ameer Dharamshi
  navbar:
    background: primary
    right:
      # - href: index.qmd
      #   text: About
      - href: pages/publications.qmd
        text: Research
      - href: pages/teaching.qmd
        text: Teaching
      - href: pages/lab.qmd
        text: Lab
      - href: pages/cv.qmd
        text: CV
      # - href: pages/resources.qmd
      #   text: Resources
      - href: pages/reading.qmd
        text: Reading List

format:
  html:
    theme: [sandstone, styles/custom.scss]
    css: styles/styles.css
    toc: true
    toc-location: right
    # toc-depth: 3
    # toc-expand: true
    smooth-scroll: true

editor: source
